osx_image: xcode9 
language: objective-c
before_install:
  - brew tap yonaskolb/mint https://github.com/yonaskolb/mint.git
  - brew install mint
script:
  - mint run realm/swiftlint@0.23.1
  - swift build
  - swift test
