use_frameworks!
target 'Bivrost_Tests' do
  pod 'Bivrost', :path => '../'
  
  pod 'Quick', :git => 'https://github.com/Quick/Quick.git'
  pod 'Nimble', :git => 'https://github.com/Quick/Nimble.git'
end
