//
//  main.swift
//  Bivrost
//
//  Created by Luis Reisewitz on 27.09.17.
//  Copyright © 2017 Gnosis. All rights reserved.
//

import Commander
import BivrostKit
import Foundation
import PathKit

func paths(from pattern: String) -> [String] {
    return Path.glob(pattern).map { $0.absolute().string }
}

extension JsonFormat: ArgumentConvertible {
    public var description: String {
        return self.rawValue
    }

    public init(parser: ArgumentParser) throws {
        if let value = parser.shift(),
            let format = JsonFormat(rawValue: value) {
            self = format
        } else {
            throw ArgumentError.missingValue(argument: nil)
        }
    }
}

let generate = command(
    Option<String>("input", default: "./abi/*.json", description: "Input file pattern specifying which json files should be parsed. Needs to be escaped with quotes to prevent the shell from expanding it."),
    Option<String>("output", default: "./solidity", description: "Output folder which will contain all necessary Solidity files (generated and auxiliary)."),
    Option<JsonFormat>("format", default: .truffle3, description: """
        Format of the json input file.
                Either `truffle3` or `solc0.4`.
                - truffle3: Truffle version 3. Generated by `truffle compile`.
                - solc0.4: Solc version 0.4. Generated by `solc --combined-json abi <file>`.
        """),
    Flag("force", default: false, flag: "f", disabledName: nil, disabledFlag: nil, description: "If set, deletes all contents of the output folder before recreating it. Make sure there is nothing else in there.")) { inputPattern, output, format, force  in
        
        let expandedPaths = paths(from: inputPattern)
        let outputFolder = Path(output).absolute().string
        do {
            try BivrostKit.generateSolidityFiles(from: expandedPaths, to: outputFolder, format: format, force: force)
        } catch {
            print("=== An error occurred during contract generation. ===")
            print("=== Error: ===")
            print(error)
        }
}

generate.run()
